// Auto-generated TypeScript types for gRPC messages (should be generated by proto-loader in real project)
export interface CreateUserRequest {
  email: string;
  name: string;
  password: string;
}

export interface GetUserRequest {
  id: string;
}

export interface UserResponse {
  id: string;
  email: string;
  name: string;
  roles: string[];
  createdAt: string;
}
